name: truth_ai
description: Une application de vÃ©rification de faits avec IA

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.10
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^13.0.0
  permission_handler: ^10.4.0
  device_info_plus: ^8.1.0
  # pour produire/recevoir messages natifs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/ForensicsModeApp.png
    - assets/images/ImageDailyApp.png
    - assets/shaders/aurora_shader.frag

  
    -
      family: Montserrat
        -
          asset: assets/fonts/Montserrat-Regular.ttf
        -
          asset: assets/fonts/Montserrat-Bold.ttf

    - assets/shaders/aurora_shader.frag
